// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompletePomodoro(arg1, arg2) {
  return window['go']['backend']['App']['CompletePomodoro'](arg1, arg2);
}

export function CreateAppMenu() {
  return window['go']['backend']['App']['CreateAppMenu']();
}

export function CreateTask(arg1, arg2) {
  return window['go']['backend']['App']['CreateTask'](arg1, arg2);
}

export function DeleteTask(arg1) {
  return window['go']['backend']['App']['DeleteTask'](arg1);
}

export function GetAppInfo() {
  return window['go']['backend']['App']['GetAppInfo']();
}

export function GetCurrentUser() {
  return window['go']['backend']['App']['GetCurrentUser']();
}

export function GetDailySummary(arg1) {
  return window['go']['backend']['App']['GetDailySummary'](arg1);
}

export function GetLanguage() {
  return window['go']['backend']['App']['GetLanguage']();
}

export function GetReport(arg1, arg2) {
  return window['go']['backend']['App']['GetReport'](arg1, arg2);
}

export function GetServerHost() {
  return window['go']['backend']['App']['GetServerHost']();
}

export function GetSessions(arg1, arg2) {
  return window['go']['backend']['App']['GetSessions'](arg1, arg2);
}

export function GetTasks() {
  return window['go']['backend']['App']['GetTasks']();
}

export function GetTimerState() {
  return window['go']['backend']['App']['GetTimerState']();
}

export function GetUserDailyRetro(arg1) {
  return window['go']['backend']['App']['GetUserDailyRetro'](arg1);
}

export function GetWaterReminderSettings() {
  return window['go']['backend']['App']['GetWaterReminderSettings']();
}

export function HideWindow() {
  return window['go']['backend']['App']['HideWindow']();
}

export function LockScreen() {
  return window['go']['backend']['App']['LockScreen']();
}

export function Login(arg1, arg2) {
  return window['go']['backend']['App']['Login'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['backend']['App']['Logout'](arg1);
}

export function MinimizeWindow() {
  return window['go']['backend']['App']['MinimizeWindow']();
}

export function PausePomodoro() {
  return window['go']['backend']['App']['PausePomodoro']();
}

export function Ping() {
  return window['go']['backend']['App']['Ping']();
}

export function PushNotification(arg1) {
  return window['go']['backend']['App']['PushNotification'](arg1);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['backend']['App']['Register'](arg1, arg2, arg3);
}

export function RestoreSession(arg1) {
  return window['go']['backend']['App']['RestoreSession'](arg1);
}

export function ResumePomodoro() {
  return window['go']['backend']['App']['ResumePomodoro']();
}

export function SaveDailyRetro(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SaveDailyRetro'](arg1, arg2, arg3);
}

export function SaveServerHost(arg1) {
  return window['go']['backend']['App']['SaveServerHost'](arg1);
}

export function SaveWaterReminderSettings(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SaveWaterReminderSettings'](arg1, arg2, arg3);
}

export function SetLanguage(arg1) {
  return window['go']['backend']['App']['SetLanguage'](arg1);
}

export function SetupSystemTray() {
  return window['go']['backend']['App']['SetupSystemTray']();
}

export function ShowWindow() {
  return window['go']['backend']['App']['ShowWindow']();
}

export function StartPomodoro(arg1, arg2) {
  return window['go']['backend']['App']['StartPomodoro'](arg1, arg2);
}

export function StopPomodoro() {
  return window['go']['backend']['App']['StopPomodoro']();
}

export function UpdateTask(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateTask'](arg1, arg2, arg3, arg4);
}
