// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';
import {backend} from '../models';

export function BackupToDrive():Promise<void>;

export function CompletePomodoro(arg1:number,arg2:any):Promise<void>;

export function CreateAppMenu():Promise<menu.Menu>;

export function CreateTask(arg1:string,arg2:string):Promise<backend.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetCurrentUser():Promise<backend.User>;

export function GetDailySummary(arg1:string):Promise<backend.DailySummary>;

export function GetLanguage():Promise<string>;

export function GetReport(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetServerHost():Promise<string>;

export function GetSessions(arg1:string,arg2:string):Promise<Array<backend.PomodoroSession>>;

export function GetTasks():Promise<Array<backend.Task>>;

export function GetTimerState():Promise<backend.TimerState>;

export function GetUserDailyRetro(arg1:string):Promise<backend.DailyRetro>;

export function GetWaterReminderSettings():Promise<backend.WaterReminderSettings>;

export function GoogleCallback(arg1:string):Promise<void>;

export function GoogleLogin():Promise<string>;

export function HasGoogleCredentials():Promise<boolean>;

export function HideWindow():Promise<void>;

export function IsGoogleAuthenticated():Promise<boolean>;

export function LockScreen():Promise<void>;

export function Login(arg1:string,arg2:string):Promise<backend.User>;

export function Logout(arg1:string):Promise<void>;

export function MinimizeWindow():Promise<void>;

export function PausePomodoro():Promise<void>;

export function Ping():Promise<string>;

export function PushNotification(arg1:backend.Notification):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestoreFromDrive():Promise<void>;

export function RestoreSession(arg1:string):Promise<backend.User>;

export function ResumePomodoro():Promise<void>;

export function SaveDailyRetro(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveGoogleClientCredentials(arg1:string,arg2:string):Promise<void>;

export function SaveServerHost(arg1:string):Promise<void>;

export function SaveWaterReminderSettings(arg1:boolean,arg2:number,arg3:any):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetupSystemTray():Promise<void>;

export function ShowWindow():Promise<void>;

export function StartPomodoro(arg1:number,arg2:any):Promise<void>;

export function StopPomodoro():Promise<void>;

export function UpdateTask(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<void>;
